### ISSUE TITLE
Different dates?

### ISSUE THREAD

**Issue by jamesliu1** [nkaz001/hftbacktest#1]
In example.py, snapshot_df uses 20220830,  whilst df uses 20220831.
Why do they use two different dates?  
Thanks.

**Comment by nkaz001** [comment]
20220830.snapshot is the market depth snapshot of the end of 20220830.
The market depth stream data Binance sends is the change from the last state.
So to build the market depth correctly, you need to process the data from the last market depth snapshot.

It's also possible to run without the snapshot but it might be not complete for a certain time.

More correctly, building the complete market depth is impossible because Binance doesn't provide the full market depth snapshot. They only give 1000-depth snapshot. But the market depth could be sufficiently complete after enough time has passed.

Please see https://github.com/nkaz001/collect-binancefutures and https://binance-docs.github.io/apidocs/futures/en/#diff-book-depth-streams

**Comment by jamesliu1** [comment]
Let's say that collect.sh generates btcusdt_20220830.dat and btcusdt_20220831.dat;
Then, convert.sh will generate four files:
  btcusdt_20220830.pkl
  btcusdt_20220830.snapshot.pkl
  btcusdt_20220831.pkl
  btcusdt_20220831.snapshot.pkl
Now, I should use btcusdt_20220830.snapshot.pkl and btcusdt_20220831.pkl for backtesting, am I right?
Thank you.

**Comment by nkaz001** [comment]
Yes, you're right.
