### ISSUE TITLE
user events

### ISSUE THREAD

**Issue by griffiri** [nkaz001/hftbacktest#15]
Hi - I am going to try out a market making strategy where one of the inputs will be the price on another exchange and would like to try to run a back test. I was wondering whether this should be done using the 'user' event type in the data feed? Or simply import a file with the data when writing the algo. I couldn't see an example of this sort of thing in the repo. thanks

**Comment by nkaz001** [comment]
I didn't have time to write an example for that, but I'll create more documents and examples.

First, you need to merge your custom data with the data feed. By using [`merge_on_local_timestamp`](https://hftbacktest.readthedocs.io/en/latest/reference/data_utilities.html#hftbacktest.data.merge_on_local_timestamp) you can effortlessly combine two datasets. Just be cautious to ensure that your custom data has invalid exchange timestamps set to `-1`; otherwise, it may lead to errors. Additionally, the event ID should be above `100`.

In the backtesting, you can retrieve by [`get_user_data`](https://hftbacktest.readthedocs.io/en/latest/reference/backtester.html#hftbacktest.backtest.SingleAssetHftBacktest.get_user_data) method of HftBacktest instance.

**Comment by griffiri** [comment]
Thanks - i'll try it out

**Comment by nkaz001** [comment]
I added the tutorial for it. Please see [here](https://hftbacktest.readthedocs.io/en/latest/tutorials/Integrating%20Custom%20Data.html).
