### ISSUE TITLE
Run backtest with and without snapshot have different results

### ISSUE THREAD

**Issue by Ray-0403** [nkaz001/hftbacktest#163]
HI, I noticed that the backtest results are quite different when I use an initial snapshot compared to when I don’t. For example, adding initial snapshot changes PnL, and SR a lot.

Why does using a snapshot make such a big difference? Is it always necessary to use a snapshot for accurate results, or are there cases where it’s fine to skip it? 

asset = (
    BacktestAsset()
        .data('/Users/r/Desktop/hftbacktest/btcusdt_20240901.npz')
        .initial_snapshot('/Users/r/Desktop/hftbacktest/btcusdt_20240831_eod.npz') 
        .linear_asset(1.0) 
        .intp_order_latency('/Users/r/Desktop/hftbacktest/btcusdt_feed_latency_20240901.npz')
        .power_prob_queue_model(2)
        .no_partial_fill_exchange()
        .trading_value_fee_model(-0.00005, 0.0007)
        .tick_size(0.1)
        .lot_size(0.001)
        .roi_lb(roi_lb)    
        .roi_ub(roi_ub)
)

with snapshot
<img width="1103" alt="with snapshot" src="https://github.com/user-attachments/assets/551ee058-daba-455f-9da8-a43ea366b0e2">

without snapshot
<img width="1054" alt="without snapshot" src="https://github.com/user-attachments/assets/653814df-35b3-4cdb-9485-12049c302801">

**Comment by nkaz001** [comment]
As shown in your plot, the most significant differences occur at the beginning because, without the initial snapshot, the market depth starts empty. Until sufficient market depth information is accumulated through natural refresh (via subsequent market depth feeds), the market depth data and, consequently, the order fill simulations, are inevitably inaccurate.

It is recommended to input an initial snapshot unless the data file already contains one at the beginning. But, this can lead to inefficiencies when backtesting across multiple consecutive days. Alternatively, you can consider the backtest results reliable after a certain period, once enough market depth information has been accumulated.
