### ISSUE TITLE
how to contribute

### ISSUE THREAD

**Issue by marsupialtail** [nkaz001/hftbacktest#20]
I would like to contribute. First I will try to understand your code.

Two questions:
- Why not just write C and build C bindings? Do you think that will improve the performance?
- I work on this library here: https://github.com/marsupialtail/quokka/blob/master/blog/orderedstreams.md. I do distributed stuff. I would be interested in supporting distributed execution of this library on cloud setup with data coming from S3. I actually tried to write something like you did in C/Python, but might as well just use your code now that I found it.

**Comment by nkaz001** [comment]
Contributions are welcome!

Regarding your first question, when I began this project, I didn't thoroughly consider all the factors.
From a research standpoint, Python appears to be the optimal choice given its wide-ranging application.
Currently, I observe several limitations with my existing Numba-based implementation, particularly when considering the implementation of multi-asset backtesting and market-by-order backtesting.

In fact, I'm rewriting some of the code in Rust. This is experimental, but I'm considering implementing the core features in Rust and providing a wrapper for usage in Numba as it is. Despite my attempts to rewrite the code in Rust, I don't anticipate a significant improvement in the performance of the current implementation beyond the JIT overhead.

Regarding your second query, would you attempt to backtest multiple assets in a distributed environment?
I ask because, without certain conditions such as liquidating all positions at the end of the day, distributing a single asset backtest in a time-wise manner seems challenging.

**Comment by marsupialtail** [comment]
There are different things you could be doing in a distributed environment, for example
- backtest multiple assets in a distributed environment and produce a consolidated trading report across time
- liquidating all positions at the end of the day may not be a good idea in crypto (seems to be your focus) but in equities it makes a lot of sense -- in this case the distribution is rather easy you just do each day in parallel
- backtesting multiple strategies in parallel (potentially thousands of them) and killing some of them early on, e.g. if you want to test different stop loss combinations

I will try to understand your library fully first -- do you plan on open sourcing the Rust?

**Comment by marsupialtail** [comment]
I would like to add that it would be interesting to build support for tick-level backtesting that only relies on trade data. Quotes data from Binance is not publicly available, and vendors like Tardis.dev are known to have problems like missing quotes in historical data.

**Comment by nkaz001** [comment]
Certainly, I will make the Rust version open-source as well. It will be uploaded to this repository in a separate branch.

Regarding backtesting based solely on trade data, I have serious doubts about its accuracy, especially when applied to short time frames. Without order book data, it could lead to severely inaccurate results. It may suggest unrealistic profit opportunities or even conceal potential ones.

In longer time frames, you might achieve results close to live, but in that case, you wouldn't need tick-by-tick backtesting and most of the complicated features implemented in hftbacktest. Simply using minutely bar or a few seconds bar data would be adequate.

Given that people can freely access order book tick data on cryptocurrency exchanges, if buying data from a vendor seems to be burdensome or unreliable, I strongly recommend that you collect the data yourself.

Without order book data, any results will lack significance. It is essential to use both trade and order book data.

**Comment by marsupialtail** [comment]
Thank you!
