### ISSUE TITLE
Not seeing results of the backtest on the graph

### ISSUE THREAD

**Issue by artiko88** [nkaz001/hftbacktest#28]
Hi!

First of, thank you for sharing this amazing piece of software. 

I am fairly new to HFT and i am probably doing something wrong. I tried to simulate a Grid Trading strategy with a skew on a few coins. Two of them are ARBUSDT perpetual and BTCUSDT perpetual. When i backtest the strategy on BTCUSDT, i get this graph:

![image](https://github.com/nkaz001/hftbacktest/assets/4704439/64351ea1-92ad-4f5b-9d8a-8ce16106c95c)

This is one day worth of data, strategy is used as it is presented in the examples folder. Here is how it is executed:

![image](https://github.com/nkaz001/hftbacktest/assets/4704439/526a8433-f6ba-4149-8396-a02ff78d52a1)

But when i try to simulate the same strategy on ARBUSDT on one weeks worth of data, here is the graph that i get:

![image](https://github.com/nkaz001/hftbacktest/assets/4704439/3e9b8e84-6ab1-4f4c-9ef5-a44eb61e3050)

It provides statistics in a text form, but doesn't provide cumulative returns neither with nor without fees. 

Here are settings that i use to start simulation:

![image](https://github.com/nkaz001/hftbacktest/assets/4704439/543d0980-6fe0-4cbf-bd7d-45c20037921e)

Data for both ARBUSDT and BTCUSDT are taken from Tardis via CSV downloads. After that i convert it using tardis.convert(). When creating a snapshot i use data from previous day compared to the day backstart starts with:

```
create_last_snapshot(f'data/ARBUSDT/{exchange}_2023-07-18.npz', 
                                tick_size=0.1, 
                                lot_size=0.000001,
                                output_snapshot_filename = f'data/ARBUSDT/{exchange}_2023-07-18_SNAPSHOT.npz')
```

What am i doing wrong?

**Comment by nkaz001** [comment]
First of all, it is essential to set the appropriate tick size and lot size. For ARBUSDT in Binance Futures, the tick size is 0.0001, and the lot size(minimum trading quantity increment) is 0.1, as displayed on the Binance Futures Trading Page.

The reason why the equity curve appears flat at zero is due to the `capital` argument in `stat.summary`.
To calculate the equity's Return%, it is divided by the capital(your invested capital).

In Futures or margin trading, leverage can be utilized; however, during the backtest, the margin level is not verified. But, in `stat`, you can observe your margin utilization based on the capital input.

Since the backtest is completely wrong due to incorrect tick size and lot size, I cannot tell anything based on your stat.
But my suggestion about order quantity and capital is as follows.
- the initial order quantity is set at 100, which is estimated based on ARBUSDT trades and market depth.
- The capital calculation would be around 1.1 (current price) * 100 (order quantity) * 50 (max position) / 1 (your leverage) = 5500, it can vary depending on your strategy and risk appetite.

Also, when creating a snapshot, ensure to input the appropriate tick size and lot size.

**Comment by artiko88** [comment]
Thanks for your participation!

Ok, so indeed i was using incorrect tick size and lot size. I looked them up alas in the wrong section of binance :)

Here is how i set up creation of snapshot and trading simulation:

```
symbol = 'ARBUSDT'
start_day = 18
exchange = 'binance-futures'

create_last_snapshot(f'data/{symbol}/{exchange}_2023-07-{start_day}.npz', 
                                tick_size=0.0001, 
                                lot_size=0.1,
                                output_snapshot_filename = f'data/{symbol}/{exchange}_2023-07-{start_day}_SNAPSHOT.npz')
```

And here is how i set up backtest:

```
hbt = HftBacktest(
    [
        'data/ARBUSDT/binance-futures_2023-07-19.npz'
    ],
    tick_size=0.0001, 
    lot_size=0.1,
    maker_fee= -0.00003,
    taker_fee= 0.00024,
    order_latency=FeedLatency(),
    queue_model=SquareProbQueueModel(),
    asset_type=Linear,
    snapshot='data/ARBUSDT/binance-futures_2023-07-18_SNAPSHOT.npz'
)

stat = Stat(hbt)

skew = 1
gridtrading(hbt, stat.recorder, skew)
stat.summary(capital=550)
```

I used _skew_ equal to 10 as well and decided to back down to 10 just to see wether it affects the output. I lowered the capital down to 550 as well. And the output is still with no cum return curve:

![image](https://github.com/nkaz001/hftbacktest/assets/4704439/6c96ec32-404b-4936-b540-3dfce53ccbe4)

It is interesting that same set up works with BTCUSDT.

**Comment by nkaz001** [comment]
According to the position plot of your stats, the position is ranging within -0.1 to 0.3, with its max value being about 1.1 * 0.3 = 0.33. Your capital set is too high.

As for the second stat, it appears that no trading occurred.

You can retrieve and check equity value using [`stat.equity()`](https://hftbacktest.readthedocs.io/en/latest/reference/stat.html#hftbacktest.stat.Stat.equity).
