### ISSUE TITLE
Simulate trades

### ISSUE THREAD

**Issue by pepi99** [nkaz001/hftbacktest#4]
I have orderbook data that looks like this:

timestamp, price, side, volume
2023-02-10 23:59:49.789,21637.48,ask,0.67350
2023-02-10 23:59:49.789,21630.66,ask,0.03474
2023-02-10 23:59:49.789,21619.44,bid,0.00000

(0 volume here means cancel order/match order, doesn't matter)

I want to simulate trades on secondly basis. In each second I can potentially place an order (a market order or a limit order) so that they can be processed by your package. Is that possible?

Regards

**Comment by nkaz001** [comment]
In order to backtest more accurately, you need trade data and two types of timestamps: local_timestamp and exch_timestamp. But, still, it's possible to backtest only based on order book data and one side of timestamps if you assume your latency and generate the other side of timestamps artificially. 

Firstly, you need to compose Pandas DataFrame based on your data. 

Please see the example of conversion: https://github.com/nkaz001/collect-binancefutures/blob/master/convert/convert.py 

columns: 'event', 'exch_timestamp', 'local_timestamp', 'side', 'price', 'qty'

event:
DEPTH_EVENT = 1
TRADE_EVENT = 2
DEPTH_CLEAR_EVENT = 3
DEPTH_SNAPSHOT_EVENT = 4

side:
BUY (BID) = 1
SELL (ASK) = -1

**Comment by pepi99** [comment]
Will give it a try, thanks!
