### ISSUE TITLE
5 LEVEL SNAPSHOT For a stock market that provides only orderbook data, how to process the data ?

### ISSUE THREAD

**Issue by bohblue2** [nkaz001/hftbacktest#55]
For the orderbook in snapshot format, we know that we need to convert it to incremental format to put the data in. 

For the stock market, the day starts at 9:00 and the regular day ends at 4:30 pm. In this case, can I ask for some guidelines on how to handle DEPTH_CLEAR_EVENT and DEPTH_SNAPSHOT_EVENT?

Also, I appreciate your open source, and would like to support you, either as a github sponsor or on Patreon would be great.

**Comment by nkaz001** [comment]
Please see https://github.com/nkaz001/hftbacktest/issues/42#issuecomment-1790886533

But, 5-level snapshot data cannot show the complete market information. For instance, US stock markets have a Market-By-Order feed. Although hftbacktest currently cannot directly process MBO feeds, it is better to convert MBO into Market-By-Price rather than converting a 5-level snapshot.

**Comment by bohblue2** [comment]
I thought I had seen all the issues, but I missed them, so thanks for the reminder.

The Orderbook snapshot information needs to be converted to a Market-By-Price type, thank you.
