### ISSUE TITLE
How to incorporate underlying coin move to make markets in some derivative?

### ISSUE THREAD

**Issue by shreyassarda7** [nkaz001/hftbacktest#64]
I came across this amazing project while looking for a HFT-backtesting framework.  I can understand this involves a **Single Asset Market-Making Model**. Is there any way to incorporate some underlying asset order book and give a logic for calculating fair for derivatives? 

It would be interesting to see this feature because currently, I'm just creating a time series of underlying assets on which the derivative market depends. Then getting the last timestamp from the _stat.timestamp_ list to get underlying value to determine what jump to apply on the Derivative fair and then put bid-ask prices that are to be backtested for market-making derivative.

I think this feature should be easy to accommodate in this framework. This can make it a pretty interesting proposition backtesting market-making strategies for ETFs, Futures, or Options as well.

**Comment by nkaz001** [comment]
Is what you mentioned about the way you deal with the underlying value similar to [this](https://hftbacktest.readthedocs.io/en/latest/tutorials/Integrating%20Custom%20Data.html#Accessing-Spot-Price)?

If so, I think it's currently the best way to deal with it because it's computationally much cheaper if you can compute the values in advance. Running a backtest for mutiple assets in a tick-by-tick manner could be much slower.

In a branch of this repo, you can find an experimental implementation in Rust for multi-asset backtesting, even though it's not thoroughly tested.

**Comment by shreyassarda7** [comment]
Hi @nkaz001, thanks for the revert. Yeah, this definitely is better than my method of slicing through pd.Series which didn't make it possible with numba. Thanks
